### ISSUE TITLE
Assigning the value N in the algorithm

### ISSUE THREAD

**Issue by phanducthien82** [zeman412/Tabu_Search_QAP_20#1]
In your algorithm, the value N = 190 is set. What do you base this value on? Why do you set it to 190?

**Comment by zeman412** [comment]
@phanducthien82 I don't think there is a fundamental rule for setting N to a specific value. Like most heuristic algorithms, certain parameters are selected based on literature or by performing series of experiments select a value for which the algorithm converges faster. Example for this algorithm, if we try different values of N, let say N=10, N=50, N=200, N=150. Then if we plot the resulting solutions, we could see the value of N for which the solution is converging faster. But since heuristic algorithms are not deterministic, there is no guarantee that specific value of N is always better. The common approach is to select several values, perform experiment, compare the convergence and pick a value accordingly.  I hope this helps.

**Comment by phanducthien82** [comment]
Thanks, I get it
